name: 'Auto Assign'
on: 
  pull_request:
    types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title for Exclusion
        id: check_pr_title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" =~ (^|[[:space:]])[Aa][Uu][Tt][Oo][Mm][Ee][Rr][Gg][Ee]([[:space:]]|$) ]]; then
            echo "excluded=true" >> $GITHUB_ENV
          else
            echo "excluded=false" >> $GITHUB_ENV
          fi

      - name: Run Auto-Assign
        if: env.excluded == 'false'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ".github/auto-assign-config.yml"
